name: engage
channels:
  - conda-forge
dependencies:
  - pip=24.2
  - python=3.10.16
  - pip:
      - hydra-core==1.3.2
      - ipykernel==6.29.5
      - jaxlib==0.4.38
      - matplotlib==3.8.4
      - networkx==2.8.8
      - numba==0.60.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pandapower==2.14.11
      - pandas==2.2.3
      - python-igraph==0.9.11
      - pyemd==1.0.0
      - seaborn==0.13.2
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - simbench==1.5.3
      - spektral==1.0.6
      - torch==2.5.1
      - torch-geometric==2.6.0
      - tqdm==4.67.1